language: ruby
rvm:
 - 1.9.3
 - 1.8.7

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/site.yml.tmpl config/site.yml"

script: "bundle exec rake ci"

bundler_args: --without development
notifications:
  recipients:
    - tracksapp@googlegroups.com

