version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    volumes:
      - "db-data:/var/lib/mysql"
  web:
    build: .
    volumes:
      - "${VOLUME:-:/app/workdir}"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:

