---
name: Automated tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: matrix
    matrix:
      ruby: ["2.5", "2.6", "2.7", "3.0"]
      db: [sqlite, mysql, postgres]
    steps:
      - uses: actions/checkout@v1
      - run: bash -x script/cibuild ${{ matrix.ruby }} ${{ matrix.db }}