---
name: Continuous Integration

on:
  pull_request:
    types: opened, edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: bash -x script/cibuild
